"""Sensortype added

Revision ID: 55fac532a46f
Revises: 
Create Date: 2025-03-25 23:38:41.042875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55fac532a46f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('block_state', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('error_value', sa.Float(), nullable=False),
    sa.Column('measurement_unit', sa.String(), nullable=False),
    sa.Column('id_device', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_device'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('id_sensor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sensor'], ['sensor_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_records')
    op.drop_table('sensor_list')
    op.drop_table('users')
    op.drop_table('sensor_types')
    op.drop_table('devices')
    # ### end Alembic commands ###
