"""Sensortype added id v 1

Revision ID: 7b1da5a138ac
Revises: 55fac532a46f
Create Date: 2025-03-25 23:46:24.463411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1da5a138ac'
down_revision: Union[str, None] = '55fac532a46f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_list', sa.Column('id_sensor_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sensor_list', 'sensor_types', ['id_sensor_type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_list', type_='foreignkey')
    op.drop_column('sensor_list', 'id_sensor_type')
    # ### end Alembic commands ###
