"""Data records on cascade

Revision ID: f814c3679de7
Revises: b21bc1307e9c
Create Date: 2025-04-15 18:52:04.407660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f814c3679de7'
down_revision: Union[str, None] = 'b21bc1307e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('data_records_id_sensor_fkey', 'data_records', type_='foreignkey')
    op.create_foreign_key(None, 'data_records', 'sensor_list', ['id_sensor'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_records', type_='foreignkey')
    op.create_foreign_key('data_records_id_sensor_fkey', 'data_records', 'sensor_list', ['id_sensor'], ['id'])
    # ### end Alembic commands ###
