"""on cascade device

Revision ID: b21bc1307e9c
Revises: 7b1da5a138ac
Create Date: 2025-03-27 22:37:45.892804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21bc1307e9c'
down_revision: Union[str, None] = '7b1da5a138ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sensor_list_id_device_fkey', 'sensor_list', type_='foreignkey')
    op.create_foreign_key(None, 'sensor_list', 'devices', ['id_device'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_list', type_='foreignkey')
    op.create_foreign_key('sensor_list_id_device_fkey', 'sensor_list', 'devices', ['id_device'], ['id'])
    # ### end Alembic commands ###
